test: MemoryService 테스트 코드
Memory-Seekers/Memory-Backend pull request #16
Opened 2023-07-27 07:14 UTC by snowfluppy

## 개요

---

- MemoryService 테스트 코

</br>

## 변경내용

---

- Id로 추억일지 리스트 조회 테스트 코드
- 친구 추억일지 리스트 조회 테스트 코드

</br>

## 리뷰 시 고려할 점

---

- 리스트 길이 조회 외에 확인하면 좋을 점이 있는가

2023-07-28 12:30 UTC, whitez1 requested changes

2023-07-28 12:30 UTC, whitez1 commented on src/test/java/lookIT/lookITspring/service/MemoryServiceTest.java
> +	public void	Id로_추억일지_리스트_조회_0개() throws Exception{
앞의 메소드와의 통일성을 위해 public void 뒤에 tab 대신 space가 더 좋을 것 같아요

2023-07-31 09:25 UTC, whitez1 approved these changes

2023-08-01 04:22 UTC, 9659tig approved these changes

2023-08-01 04:55 UTC, merged