test: 내가 태그된 추억네컷 리스트 조회
Memory-Seekers/Memory-Backend pull request #18
Opened 2023-07-29 02:13 UTC by 9659tig

## 개요

---

- 내가 태그된 추억네컷 리스트 조회 테스트 코드

</br>

## 변경내용

---

- 내가 태그된 추억네컷 리스트 조회 테스트 코드

</br>

## 리뷰 시 고려할 점

---

- 사이즈 비교만으로 충분할지?

2023-07-31 08:01 UTC, snowfluppy requested changes

2023-07-31 08:01 UTC, snowfluppy commented on src/test/java/lookIT/lookITspring/controller/Photo4cutControllerTest.java
> +        assertEquals(1,collections.size());
더 비교하려면 photo4CutId, 유저 정보, 랜드마크 정보를 확인해볼 수 있을 것 같아요

2023-08-01 04:54 UTC, snowfluppy approved these changes
😊

2023-08-02 06:29 UTC, whitez1 approved these changes

2023-08-02 06:29 UTC, merged