test: LandmarkService 테스트 코드
Memory-Seekers/Memory-Backend pull request #9
Opened 2023-07-20 11:20 UTC by snowfluppy

## 개요

---

- LandmarkService 테스트 코드 수정

</br>

## 변경내용

---

- Mockito 사용 -> 사용하지 않도록 수정

</br>

## 리뷰 시 고려할 점

---

- 기존 레포지토리에 있는 값을 별도로 삭제하지 않고 그냥 새로운 값을 추가로 저장하도록 했는데 문제가 없을지
- 코드를 더 간략하게 만들 수 있는 방법이 있는지

2023-07-21 09:38 UTC, 9659tig commented
랜드마크 리스트 테스트할 때 랜드마크가 2개면 리스트에 반환되는게 2개인지 체크하는게 좋지 않을까 싶어요. 그 후에 각 리스트 요소의 경도 위도 값들을 가져와서 정확한 값인지 체크하는 방식이 해당 api 목적에 더 적합할 것 같다는 개인적인 생각입니다!
현재로서는 왜 리스트 사이즈 비교를 6개로 했는지 정확히 모르겠고 각각 랜드마크를 findByLandmarkName로 불러와서 비교하는데 이 방식은 랜드마크 리스트조회보다는 상세 조회에서만 사용하는게 좋지 않을까요?
그리고 랜드마크 ID로 상세조회한다고 되어있는데 findByLandmarkName을 사용하는 이유가 있는지, 목적에 적합한지 궁금합니다!
테스트 코드 짜느라 고생하셨어요...!

2023-07-22 06:53 UTC, 9659tig requested changes

2023-07-22 06:53 UTC, 9659tig commented on src/test/java/lookIT/lookITspring/service/LandmarkServiceTest.java
> +        Landmark checkLandmark = landmarkRepository.findByLandmarkName("테스트용 랜드마크3");
랜드마크_ID로_상세정보_조회 테스트이기 때문에 getLandmarkID등으로 랜드마크 id를 불러온다음
랜드마크 ID로 데이터를 불러오는게 좋을 것 같습니다!

2023-07-22 06:55 UTC, snowfluppy commented on src/test/java/lookIT/lookITspring/service/LandmarkServiceTest.java
> +        Landmark checkLandmark = landmarkRepository.findByLandmarkName("테스트용 랜드마크3");
수정하겠습니다

2023-07-22 07:00 UTC, whitez1 requested changes

2023-07-22 07:00 UTC, whitez1 commented on src/test/java/lookIT/lookITspring/service/LandmarkServiceTest.java
> +        Landmark checkLandmark1 = landmarkRepository.findByLandmarkName("테스트용 랜드마크1");
AllLandmarkDto landmark1 = allLandmarks.get(allLandmarks.size()-2);

2023-07-22 07:00 UTC, whitez1 commented on src/test/java/lookIT/lookITspring/service/LandmarkServiceTest.java
> +        Landmark checkLandmark2 = landmarkRepository.findByLandmarkName("테스트용 랜드마크2");
AllLandmarkDto landmark2 = allLandmarks.get(allLandmarks.size()-1);

2023-07-22 07:00 UTC, whitez1 commented on src/test/java/lookIT/lookITspring/service/LandmarkServiceTest.java
> +        assertEquals("Assertion failed: Landmark1 Latitude mismatch", 18.1111354, checkLandmark1.getLandLatitude());
assertEquals("Assertion failed: Landmark1 Latitude mismatch", 18.1111354, landmark1.getLandLatitude()
);

2023-07-22 07:00 UTC, whitez1 commented on src/test/java/lookIT/lookITspring/service/LandmarkServiceTest.java
> +        landmarkRepository.save(landmark2);
위의 코드는 준비하는 과정이므로 Given에 들어가는 것이 적합할 듯 합니다:)

2023-07-22 08:34 UTC, snowfluppy commented
리뷰 반영하여 수정하였습니다

2023-07-22 13:10 UTC, whitez1 approved these changes

2023-07-22 13:29 UTC, 9659tig approved these changes

2023-07-22 13:29 UTC, merged